name: Build, Encrypt, and Deploy TypeScript

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies and compile
        run: |
          bun install
          bun build --compile --minify-whitespace --minify-syntax ./src/app.ts --outfile serverPilot

      - name: Upload compiled file
        uses: actions/upload-artifact@v4
        with:
          name: serverPilot
          path: serverPilot
